import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  buildDefinitionHeader,
  parseDefinitionHeader,
  leadingCommentBlock,
  PLUGIN_VERSION,
  SPEC_VERSION
} from '../scripts/buildDefinitionHeader.mjs';

test('PLUGIN_VERSION: plugin.json과 일치', async () => {
  const { readFile } = await import('node:fs/promises');
  const pkg = JSON.parse(await readFile(new URL('../.claude-plugin/plugin.json', import.meta.url)));
  assert.equal(PLUGIN_VERSION, pkg.version);
});

test('buildDefinitionHeader: 5줄 헤더 생성 (definitionVersion 포함)', () => {
  const out = buildDefinitionHeader({
    generatedAt: '2026-06-09T10:00:00Z',
    status: 'draft',
    sources: [
      { type: 'figma', locator: '0:1', role: 'design' },
      { type: 'markdown', locator: './req.md' }
    ],
    definitionVersion: 1
  });
  const lines = out.split('\n');
  assert.equal(lines.length, 5);
  assert.match(lines[0], /<!-- Generated by dt-devspec@/);
  assert.match(lines[0], / at 2026-06-09T10:00:00Z -->/);
  assert.equal(lines[1], '<!-- status: draft -->');
  assert.equal(lines[2], '<!-- sources: figma:0:1@design, markdown:./req.md -->');
  assert.equal(lines[3], '<!-- specVersion: 1.2 -->');
  assert.equal(lines[4], '<!-- definitionVersion: 1 -->');
});

test('buildDefinitionHeader: definitionVersion이 양의 정수가 아니면 거부', () => {
  assert.throws(() => buildDefinitionHeader({
    generatedAt: '2026-06-09T10:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1' }],
    definitionVersion: 'v1'
  }), /definitionVersion must be a positive integer/);
});

test('buildDefinitionHeader: 잘못된 status 거부', () => {
  assert.throws(() => buildDefinitionHeader({
    generatedAt: '2026-06-09T10:00:00Z',
    status: 'invalid',
    sources: [{ type: 'figma', locator: '0:1' }],
    definitionVersion: 1
  }), /status must be 'finalized' or 'draft'/);
});

test('parseDefinitionHeader: 라운드트립 (definitionVersion 정수 파싱)', () => {
  const md = buildDefinitionHeader({
    generatedAt: '2026-06-09T10:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    definitionVersion: 3
  }) + '\n\n# 개발 정의서: demo';
  const parsed = parseDefinitionHeader(md);
  assert.ok(parsed);
  assert.equal(parsed.status, 'draft');
  assert.equal(parsed.specVersion, '1.2');
  assert.equal(parsed.definitionVersion, 3);
  assert.equal(typeof parsed.definitionVersion, 'number');
});

test('parseDefinitionHeader: 매칭 실패 시 null', () => {
  assert.equal(parseDefinitionHeader('# no header'), null);
});

test('parseDefinitionHeader: specVersion 줄 없어도 나머지 보존(specVersion만 null)', () => {
  const md = [
    '<!-- Generated by dt-devspec@0.8.0 at 2026-06-10T00:00:00Z -->',
    '<!-- status: draft -->',
    '<!-- sources: figma:0:1@design -->',
    '<!-- definitionVersion: 3 -->',
    '',
    '# 개발 정의서'
  ].join('\n');
  const h = parseDefinitionHeader(md);
  assert.ok(h, '헤더가 파싱되어야 함(Generated 마커 존재)');
  assert.equal(h.specVersion, null);
  assert.equal(h.definitionVersion, 3);
  assert.equal(h.status, 'draft');
});

test('parseDefinitionHeader: definitionVersion 줄 없어도 나머지 보존', () => {
  const md = [
    '<!-- Generated by dt-devspec@0.8.0 at 2026-06-10T00:00:00Z -->',
    '<!-- status: draft -->',
    '<!-- sources: figma:0:1@design -->',
    '<!-- specVersion: 1.0 -->',
    '',
    '# x'
  ].join('\n');
  const h = parseDefinitionHeader(md);
  assert.ok(h);
  assert.equal(h.specVersion, '1.0');
  assert.equal(h.definitionVersion, null);
});

test('parseDefinitionHeader: Generated 마커 없으면 null(=hand-authored 신호)', () => {
  assert.equal(parseDefinitionHeader('# 손으로 쓴 정의서\n## 전역 규약'), null);
});

test('parseDefinitionHeader: Generated 줄 trailing space 있어도 파싱(앵커 엄격도가 구버전 보존 안 깸)', () => {
  const md = '<!-- Generated by dt-devspec@0.7.0 at 2026-06-09T10:00:00Z -->   \n<!-- status: draft -->\n\n# x';
  const h = parseDefinitionHeader(md);
  assert.ok(h, 'trailing space 헤더도 generated로 파싱');
  assert.equal(h.pluginVersion, '0.7.0');
});

test('parseDefinitionHeader: 본문에 박힌 위조 마커는 헤더 블록 밖이라 무시', () => {
  const md = [
    '# 손작성',
    '',
    '본문 메모: <!-- Generated by dt-devspec@9.9.9 at x -->',
  ].join('\n');
  assert.equal(parseDefinitionHeader(md), null);
});

test('SPEC_VERSION export 존재 + 값 고정', () => {
  assert.equal(typeof SPEC_VERSION, 'string');
  assert.equal(SPEC_VERSION, '1.2'); // 값 오변경(예: 실수로 1.1로 되돌림/2.0) 회귀 차단
});

test('buildDefinitionHeader: scope 있으면 6번째 줄 emit', () => {
  const out = buildDefinitionHeader({
    generatedAt: '2026-06-16T10:00:00Z',
    status: 'finalized',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    definitionVersion: 2,
    scope: 'backoffice'
  });
  const lines = out.split('\n');
  assert.equal(lines.length, 6);
  assert.equal(lines[5], '<!-- scope: backoffice -->');
});

test('buildDefinitionHeader: scope 없으면 5줄 유지 (회귀)', () => {
  const out = buildDefinitionHeader({
    generatedAt: '2026-06-16T10:00:00Z',
    status: 'finalized',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    definitionVersion: 2
  });
  const lines = out.split('\n');
  assert.equal(lines.length, 5);
  assert.ok(!/scope/.test(out));
});

test('parseDefinitionHeader: scope round-trip', () => {
  const md = buildDefinitionHeader({
    generatedAt: '2026-06-16T10:00:00Z',
    status: 'finalized',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    definitionVersion: 2,
    scope: 'front-service'
  }) + '\n\n# 개발 정의서: front';
  const h = parseDefinitionHeader(md);
  assert.ok(h);
  assert.equal(h.scope, 'front-service');
  assert.equal(h.definitionVersion, 2);
});

test('parseDefinitionHeader: scope 없으면 scope null', () => {
  const md = buildDefinitionHeader({
    generatedAt: '2026-06-16T10:00:00Z',
    status: 'finalized',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    definitionVersion: 2
  }) + '\n\n# 개발 정의서';
  const h = parseDefinitionHeader(md);
  assert.ok(h);
  assert.equal(h.scope, null);
});

test('leadingCommentBlock: 첫 빈 줄/비-주석 줄에서 종료 (본문 주석 오탐 방지 계약)', () => {
  const md = '<!-- a -->\n<!-- b -->\n\n<!-- c -->\n# body';
  assert.equal(leadingCommentBlock(md), '<!-- a -->\n<!-- b -->'); // 빈 줄 뒤 <!-- c -->는 미포함
});

test('buildDefinitionHeader: scope 빈 문자열이면 scope 줄 미emit (5줄)', () => {
  const out = buildDefinitionHeader({
    generatedAt: '2026-06-16T10:00:00Z',
    status: 'finalized',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    definitionVersion: 2,
    scope: ''
  });
  assert.equal(out.split('\n').length, 5);
  assert.ok(!/<!-- scope:/.test(out));
});
