import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  buildSpecHeader,
  parseSpecHeader,
  PLUGIN_VERSION
} from '../scripts/buildSpecHeader.mjs';

// Test 1: PLUGIN_VERSION consistency
test('PLUGIN_VERSION: plugin.json과 일치', async () => {
  const { readFile } = await import('node:fs/promises');
  const pkg = JSON.parse(await readFile(new URL('../.claude-plugin/plugin.json', import.meta.url)));
  assert.equal(PLUGIN_VERSION, pkg.version);
});

// Test 2: buildSpecHeader with sources array (new multi-source format)
test('buildSpecHeader: sources 배열로 다중 소스 지원 (1.1 포맷)', () => {
  const out = buildSpecHeader({
    generatedAt: '2026-05-27T10:00:00Z',
    status: 'finalized',
    sources: [
      { type: 'figma', locator: '235:1412', role: 'design' },
      { type: 'markdown', locator: './req.md' }
    ]
  });
  const lines = out.split('\n');
  assert.equal(lines.length, 4, 'Should have 4 lines');
  assert.match(lines[0], /<!-- Generated by dt-spec@/, 'Line 0: brand is dt-spec@');
  assert.match(lines[0], / at 2026-05-27T10:00:00Z -->/, 'Line 0: has generatedAt');
  assert.equal(lines[1], '<!-- status: finalized -->', 'Line 1: status');
  // WHY: sources line contains multi-source comma-space-joined, with role suffix and optional loadFailed note
  assert.equal(lines[2], '<!-- sources: figma:235:1412@design, markdown:./req.md -->', 'Line 2: sources format');
  assert.equal(lines[3], '<!-- specVersion: 1.1 -->', 'Line 3: specVersion 1.1');
});

// Test 3: buildSpecHeader with draft status
test('buildSpecHeader: draft 상태도 지원', () => {
  const out = buildSpecHeader({
    generatedAt: '2026-05-27T10:00:00Z',
    status: 'draft',
    sources: [
      { type: 'figma', locator: '1:234', role: 'design' }
    ]
  });
  assert.match(out, /status: draft/);
  assert.match(out, /specVersion: 1.1/);
});

// Test 4: buildSpecHeader rejects invalid status
test('buildSpecHeader: 잘못된 status 거부', () => {
  assert.throws(() => buildSpecHeader({
    generatedAt: '2026-05-27T10:00:00Z',
    status: 'invalid',
    sources: [{ type: 'figma', locator: '1:234' }]
  }), /status must be 'finalized' or 'draft'/);
});

// Test 5: parseSpecHeader with NEW 1.1 format (sources array round-trip)
test('parseSpecHeader: 새 1.1 포맷 파싱 (sources 배열 라운드트립)', () => {
  const md = `<!-- Generated by figma-ux-spec@0.3.0 at 2026-05-27T10:00:00Z -->
<!-- status: finalized -->
<!-- sources: figma:235:1412@design, markdown:./req.md -->
<!-- specVersion: 1.1 -->

# Requirements: LoginPage
...`;
  const parsed = parseSpecHeader(md);
  assert.ok(parsed, 'Should parse header');
  assert.equal(parsed.brand, 'figma-ux-spec', 'brand is figma-ux-spec');
  assert.equal(parsed.pluginVersion, '0.3.0');
  assert.equal(parsed.generatedAt, '2026-05-27T10:00:00Z');
  assert.equal(parsed.status, 'finalized');
  assert.equal(parsed.specVersion, '1.1');
  // WHY: sources is an array with type, locator, and optional role fields
  assert.ok(Array.isArray(parsed.sources), 'sources should be array');
  assert.equal(parsed.sources.length, 2);
  assert.deepEqual(parsed.sources[0], { type: 'figma', locator: '235:1412', role: 'design' });
  assert.deepEqual(parsed.sources[1], { type: 'markdown', locator: './req.md' });
});

// Test 6: parseSpecHeader with OLD 1.0 format (backward compatibility + migration)
test('parseSpecHeader: 이전 1.0 포맷 파싱 및 마이그레이션', () => {
  const md = `<!-- Generated by figma-ux-spec@0.1.0 at 2026-05-27T10:00:00Z -->
<!-- status: finalized -->
<!-- sources: figmaPageNodeId=1:234, figmaUxWireframeNodeId=2:456 -->
<!-- specVersion: 1.0 -->

# Requirements: LoginPage
...`;
  const parsed = parseSpecHeader(md);
  assert.ok(parsed, 'Should parse 1.0 header');
  assert.equal(parsed.brand, 'figma-ux-spec');
  assert.equal(parsed.pluginVersion, '0.1.0');
  assert.equal(parsed.generatedAt, '2026-05-27T10:00:00Z');
  assert.equal(parsed.status, 'finalized');
  assert.equal(parsed.specVersion, '1.0');
  // WHY: 1.0 format migrated to sources array with design/wireframe roles
  assert.ok(Array.isArray(parsed.sources), 'sources should be normalized to array');
  assert.equal(parsed.sources.length, 2);
  assert.deepEqual(parsed.sources[0], { type: 'figma', locator: '1:234', role: 'design' });
  assert.deepEqual(parsed.sources[1], { type: 'figma', locator: '2:456', role: 'wireframe' });
});

// Test 7: parseSpecHeader accepts dt-spec@ brand (forward-compat)
test('parseSpecHeader: dt-spec@ 브랜드도 수용 (상위호환성)', () => {
  const md = `<!-- Generated by dt-spec@1.0.0 at 2026-05-27T10:00:00Z -->
<!-- status: draft -->
<!-- sources: figma:100:200@design, web:https://notion.so/x (load-failed) -->
<!-- specVersion: 1.1 -->

# Page spec`;
  const parsed = parseSpecHeader(md);
  assert.ok(parsed, 'Should parse dt-spec@ brand');
  assert.equal(parsed.brand, 'dt-spec', 'brand is dt-spec');
  assert.equal(parsed.pluginVersion, '1.0.0');
  assert.equal(parsed.status, 'draft');
  assert.equal(parsed.specVersion, '1.1');
  assert.equal(parsed.sources.length, 2);
  assert.deepEqual(parsed.sources[0], { type: 'figma', locator: '100:200', role: 'design' });
  // WHY: loadFailed is true when (load-failed) is present in sources string
  assert.deepEqual(parsed.sources[1], { type: 'web', locator: 'https://notion.so/x', loadFailed: true });
});

// Test 8: parseSpecHeader returns null on non-matching text
test('parseSpecHeader: 매칭 실패 시 null 반환', () => {
  const md = `# Just some markdown
No header here`;
  const parsed = parseSpecHeader(md);
  assert.equal(parsed, null, 'Should return null for non-matching text');
});

// Test 9: buildSpecHeader with role and loadFailed
test('buildSpecHeader: role과 loadFailed 옵션 지원', () => {
  const out = buildSpecHeader({
    generatedAt: '2026-06-02T14:30:00Z',
    status: 'finalized',
    sources: [
      { type: 'figma', locator: '235:1412', role: 'design' },
      { type: 'web', locator: 'https://notion.so/page', loadFailed: true },
      { type: 'markdown', locator: './spec.md' }
    ]
  });
  const lines = out.split('\n');
  // WHY: sources line should have role suffix (@role) and loadFailed note ( (load-failed))
  assert.equal(
    lines[2],
    '<!-- sources: figma:235:1412@design, web:https://notion.so/page (load-failed), markdown:./spec.md -->',
    'sources format with role, loadFailed, and multi-source comma-space join'
  );
});

// Test 10: buildSpecHeader without definitionVersion → legacy 4-line header (regression)
test('buildSpecHeader: definitionVersion 미전달 시 기존 4줄 헤더 (회귀 보존)', () => {
  const out = buildSpecHeader({
    generatedAt: '2026-06-09T10:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }]
  });
  const lines = out.split('\n');
  assert.equal(lines.length, 4);
  assert.equal(lines[3], '<!-- specVersion: 1.1 -->');
});

// Test 11: buildSpecHeader with definitionVersion → 5th line basedOnDefinition emit
test('buildSpecHeader: definitionVersion 전달 시 5번째 줄 basedOnDefinition emit', () => {
  const out = buildSpecHeader({
    generatedAt: '2026-06-09T10:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    definitionVersion: 3
  });
  const lines = out.split('\n');
  assert.equal(lines.length, 5);
  assert.equal(lines[3], '<!-- specVersion: 1.1 -->');
  assert.equal(lines[4], '<!-- basedOnDefinition: 3 -->');
});

// Test 12: buildSpecHeader rejects non-positive-integer definitionVersion
test('buildSpecHeader: definitionVersion이 양의 정수가 아니면 거부', () => {
  assert.throws(() => buildSpecHeader({
    generatedAt: '2026-06-09T10:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1' }],
    definitionVersion: 'v3'
  }), /definitionVersion must be a positive integer/);
});

test('buildSpecHeader: 신규격 — definitionPath+ifIds 전달 시 경로형 basedOnDefinition emit', () => {
  const out = buildSpecHeader({
    generatedAt: '2026-07-15T10:00:00Z',
    status: 'finalized',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    definitionVersion: 1,
    definitionPath: '../../definition.md',
    definitionIfIds: ['IF-4', 'IF-15']
  });
  const lines = out.split('\n');
  assert.equal(lines.length, 5);
  assert.equal(lines[4], '<!-- basedOnDefinition: ../../definition.md@v1 | IF-4,IF-15 -->');
});

test('buildSpecHeader: 신규격 — IF 리스트 비면 " | " 부분 생략', () => {
  const out = buildSpecHeader({
    generatedAt: '2026-07-15T10:00:00Z',
    status: 'finalized',
    sources: [{ type: 'figma', locator: '0:1' }],
    definitionVersion: 2,
    definitionPath: '../../definition.md'
  });
  assert.match(out, /<!-- basedOnDefinition: \.\.\/\.\.\/definition\.md@v2 -->/);
});

test('buildSpecHeader: 신규격 — definitionPath만 있고 version 없으면 거부', () => {
  assert.throws(() => buildSpecHeader({
    generatedAt: '2026-07-15T10:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1' }],
    definitionPath: '../../definition.md'
  }), /definitionPath requires definitionVersion/);
});

test('buildSpecHeader: definitionSOT=none → 경고 주석 emit, basedOnDefinition 생략', () => {
  const h = buildSpecHeader({
    generatedAt: '2026-06-15T00:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1' }],
    definitionSOT: 'none'
  });
  assert.match(h, /<!-- definitionSOT: none -->/);
  assert.ok(!/basedOnDefinition/.test(h));
});

test('buildSpecHeader: definitionSOT=unstructured → 경고 주석', () => {
  const h = buildSpecHeader({
    generatedAt: '2026-06-15T00:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1' }],
    definitionSOT: 'unstructured'
  });
  assert.match(h, /<!-- definitionSOT: unstructured -->/);
});

test('buildSpecHeader: definitionSOT 없으면 기존 동작(경고 주석 없음)', () => {
  const h = buildSpecHeader({
    generatedAt: '2026-06-15T00:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1' }],
    definitionVersion: 4
  });
  assert.ok(!/definitionSOT/.test(h));
  assert.match(h, /<!-- basedOnDefinition: 4 -->/);
});

test('buildSpecHeader: 잘못된 definitionSOT 값 거부', () => {
  assert.throws(() => buildSpecHeader({
    generatedAt: '2026-06-15T00:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1' }],
    definitionSOT: 'partial'
  }), /definitionSOT must be 'none' or 'unstructured'/);
});

test('buildSpecHeader: definitionSOT가 definitionVersion보다 우선(상호 배타 계약 잠금)', () => {
  const h = buildSpecHeader({
    generatedAt: '2026-06-15T00:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1' }],
    definitionSOT: 'none',
    definitionVersion: 4
  });
  assert.match(h, /<!-- definitionSOT: none -->/);
  assert.ok(!/basedOnDefinition/.test(h)); // definitionSOT 우선 → basedOnDefinition 억제
});

test('buildSpecHeader: scope는 헤더 마지막 줄에 emit (basedOnDefinition 뒤)', () => {
  const out = buildSpecHeader({
    generatedAt: '2026-06-16T10:00:00Z',
    status: 'finalized',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    definitionVersion: 3,
    scope: 'backoffice'
  });
  const lines = out.split('\n');
  assert.equal(lines.length, 6);
  assert.equal(lines[3], '<!-- specVersion: 1.1 -->');
  assert.equal(lines[4], '<!-- basedOnDefinition: 3 -->');
  assert.equal(lines[5], '<!-- scope: backoffice -->'); // scope는 마지막
});

test('buildSpecHeader: scope만 있고 definitionVersion·definitionSOT 둘 다 없으면 specVersion 다음 줄(5줄)', () => {
  const out = buildSpecHeader({
    generatedAt: '2026-06-16T10:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    scope: 'front-service'
  });
  const lines = out.split('\n');
  assert.equal(lines.length, 5);
  assert.equal(lines[3], '<!-- specVersion: 1.1 -->');
  assert.equal(lines[4], '<!-- scope: front-service -->');
});

test('buildSpecHeader: scope 없으면 기존 동작 (회귀)', () => {
  const out = buildSpecHeader({
    generatedAt: '2026-06-16T10:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    definitionVersion: 3
  });
  assert.ok(!/scope/.test(out));
  assert.match(out, /<!-- basedOnDefinition: 3 -->/);
});

test('parseSpecHeader: scope round-trip (scope 있어도 brand/specVersion/sources 정상 파싱)', () => {
  const md = buildSpecHeader({
    generatedAt: '2026-06-16T10:00:00Z',
    status: 'finalized',
    sources: [{ type: 'figma', locator: '235:1412', role: 'design' }],
    definitionVersion: 3,
    scope: 'backoffice'
  }) + '\n\n# Requirements: AdminPage';
  const parsed = parseSpecHeader(md);
  assert.ok(parsed, 'scope가 헤더 끝이라 HEADER_REGEX 파손 없이 파싱돼야');
  assert.equal(parsed.brand, 'dt-spec');
  assert.equal(parsed.specVersion, '1.1');
  assert.equal(parsed.sources.length, 1);
  assert.equal(parsed.scope, 'backoffice');
});

test('parseSpecHeader: scope 없으면 scope null', () => {
  const md = buildSpecHeader({
    generatedAt: '2026-06-16T10:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    definitionVersion: 3
  }) + '\n\n# x';
  const parsed = parseSpecHeader(md);
  assert.ok(parsed);
  assert.equal(parsed.scope, null);
});

test('parseSpecHeader: 본문에 박힌 scope 주석은 헤더 블록 밖이라 무시(오탐 방지)', () => {
  const md = `<!-- Generated by dt-spec@1.0.0 at 2026-06-16T10:00:00Z -->
<!-- status: draft -->
<!-- sources: figma:0:1@design -->
<!-- specVersion: 1.1 -->

# Page spec
본문 메모: <!-- scope: hacked -->`;
  const parsed = parseSpecHeader(md);
  assert.ok(parsed);
  assert.equal(parsed.scope, null); // 본문 scope는 무시
});

test('buildSpecHeader: scope 빈 문자열이면 scope 줄 미emit', () => {
  const out = buildSpecHeader({
    generatedAt: '2026-06-16T10:00:00Z',
    status: 'draft',
    sources: [{ type: 'figma', locator: '0:1', role: 'design' }],
    definitionVersion: 3,
    scope: ''
  });
  assert.ok(!/<!-- scope:/.test(out));
  assert.match(out, /<!-- basedOnDefinition: 3 -->/);
});

test('실증: scope를 specVersion 앞에 두면 HEADER_REGEX 파손(= 마지막 emit 정당성)', () => {
  // WHY: 이 배치는 buildSpecHeader가 절대 만들지 않는 잘못된 순서. 수동 구성해
  //      "왜 scope를 헤더 끝에 두는가"를 회귀로 잠근다.
  const broken = `<!-- Generated by dt-spec@1.0.0 at 2026-06-16T10:00:00Z -->
<!-- status: draft -->
<!-- sources: figma:0:1@design -->
<!-- scope: backoffice -->
<!-- specVersion: 1.1 -->

# x`;
  assert.equal(parseSpecHeader(broken), null, 'scope가 specVersion 앞이면 파손 → null');
});
