import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { checkDefinitionGate } from '../scripts/checkDefinitionGate.mjs';

function tmpProject() {
  return mkdtempSync(join(tmpdir(), 'defgate-'));
}

const DEF = `<!-- Generated by dt-devspec@0.7.0 at 2026-06-09T10:00:00Z -->
<!-- status: draft -->
<!-- sources: figma:0:1@design -->
<!-- specVersion: 1.2 -->
<!-- definitionVersion: 2 -->

# 개발 정의서: demo
## 전역 규약 (Global Conventions)
## 범위 분담 (Scope Split)
| ID | x |
| SP-1 | x |
## 인터페이스 합의 (Interface Contract)
| ID | 엔드포인트 | 합의 상태 |
| IF-1 | /api/demo | 확정 |
## 변경 추적 (Traceability)
`;

test('정의서 없음: kind=none (차단 아님)', () => {
  const root = tmpProject();
  const r = checkDefinitionGate({ projectRoot: root });
  assert.equal(r.kind, 'none');
  rmSync(root, { recursive: true, force: true });
});

test('정상 generated: kind=consume + 메타', () => {
  const root = tmpProject();
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  writeFileSync(join(root, 'docs', 'specs', 'definition.md'), DEF);
  const r = checkDefinitionGate({ projectRoot: root });
  assert.equal(r.kind, 'consume');
  assert.equal(r.authorKind, 'generated');
  assert.equal(r.definitionVersion, 2);
  assert.ok(r.path.endsWith('definition.md'));
  assert.equal(r.migrate, undefined); // 현행 버전 generated엔 migrate 키 없음(조건부 스프레드 계약)
  rmSync(root, { recursive: true, force: true });
});

test('generated인데 구조 깨짐: kind=corrupt', () => {
  const root = tmpProject();
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  const broken = '<!-- Generated by dt-devspec@0.8.0 at 2026-06-10T00:00:00Z -->\n<!-- status: draft -->\n<!-- sources: figma:0:1 -->\n<!-- specVersion: 1.2 -->\n<!-- definitionVersion: 1 -->\n# 깨짐';
  writeFileSync(join(root, 'docs', 'specs', 'definition.md'), broken);
  const r = checkDefinitionGate({ projectRoot: root });
  assert.equal(r.kind, 'corrupt');
  rmSync(root, { recursive: true, force: true });
});

test('손작성인데 구조 깨짐(산문): kind=needsNormalization', () => {
  const root = tmpProject();
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  writeFileSync(join(root, 'docs', 'specs', 'definition.md'), '# 대충 쓴 정의서\n산문만 있음');
  const r = checkDefinitionGate({ projectRoot: root });
  assert.equal(r.kind, 'needsNormalization');
  rmSync(root, { recursive: true, force: true });
});

test('구버전 generated(specVersion 1.0): kind=consume + migrate', () => {
  const root = tmpProject();
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  writeFileSync(join(root, 'docs', 'specs', 'definition.md'), DEF.replace('<!-- specVersion: 1.2 -->', '<!-- specVersion: 1.0 -->'));
  const r = checkDefinitionGate({ projectRoot: root });
  assert.equal(r.kind, 'consume');
  assert.equal(r.migrate, 'in-memory');
  rmSync(root, { recursive: true, force: true });
});

test('구버전 generated(specVersion 1.1, bump 후): kind=consume + migrate', () => {
  // SPEC_VERSION 1.2 bump 후 1.1은 구버전 → 읽기전용 흡수(migrate). 데드락 없이 전환 회귀 잠금.
  const root = tmpProject();
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  writeFileSync(join(root, 'docs', 'specs', 'definition.md'), DEF.replace('<!-- specVersion: 1.2 -->', '<!-- specVersion: 1.1 -->'));
  const r = checkDefinitionGate({ projectRoot: root });
  assert.equal(r.kind, 'consume');
  assert.equal(r.migrate, 'in-memory');
  rmSync(root, { recursive: true, force: true });
});

test('미래 버전(specVersion 9.9): kind=versionTooHigh', () => {
  const root = tmpProject();
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  writeFileSync(join(root, 'docs', 'specs', 'definition.md'), DEF.replace('<!-- specVersion: 1.2 -->', '<!-- specVersion: 9.9 -->'));
  const r = checkDefinitionGate({ projectRoot: root });
  assert.equal(r.kind, 'versionTooHigh');
  rmSync(root, { recursive: true, force: true });
});

test('하한: specVersion 0.9 (sub-1.0)는 versionTooHigh로 차단', () => {
  const root = tmpProject();
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  writeFileSync(join(root, 'docs', 'specs', 'definition.md'), DEF.replace('<!-- specVersion: 1.2 -->', '<!-- specVersion: 0.9 -->'));
  const r = checkDefinitionGate({ projectRoot: root });
  assert.equal(r.kind, 'versionTooHigh');
  rmSync(root, { recursive: true, force: true });
});

test('손작성 정상: kind=consume + authorKind:hand-authored (null deref 회귀 가드)', () => {
  const root = tmpProject();
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  const hand = '## 전역 규약\n## 범위 분담\n## 인터페이스 합의\n| IF-1 | 파일 조회 | 협의중 |\n## 변경 추적\n';
  writeFileSync(join(root, 'docs', 'specs', 'definition.md'), hand);
  const r = checkDefinitionGate({ projectRoot: root });
  assert.equal(r.kind, 'consume');
  assert.equal(r.authorKind, 'hand-authored');
  assert.equal(r.definitionVersion, null);  // 헤더 없음 → null, 크래시 없어야
  assert.equal(r.migrate, undefined); // kind!=='generated' && specVersion==null → isOldGenerated 2번째 절 미충족
  rmSync(root, { recursive: true, force: true });
});

test('scope 지정: definition.<scope>.md 해소 → consume', () => {
  const root = tmpProject();
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  writeFileSync(join(root, 'docs', 'specs', 'definition.backoffice.md'), DEF);
  const r = checkDefinitionGate({ projectRoot: root, scope: 'backoffice' });
  assert.equal(r.kind, 'consume');
  assert.ok(r.path.endsWith('definition.backoffice.md'));
  rmSync(root, { recursive: true, force: true });
});

test('scope 지정인데 그 스코프 파일 없음(bare만 있음): kind=none', () => {
  const root = tmpProject();
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  writeFileSync(join(root, 'docs', 'specs', 'definition.md'), DEF);
  const r = checkDefinitionGate({ projectRoot: root, scope: 'backoffice' });
  assert.equal(r.kind, 'none'); // bare는 backoffice 스코프가 아니므로 해소 안 됨
  rmSync(root, { recursive: true, force: true });
});

test('scope 미지정: 기존대로 definition.md (하위호환)', () => {
  const root = tmpProject();
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  writeFileSync(join(root, 'docs', 'specs', 'definition.md'), DEF);
  const r = checkDefinitionGate({ projectRoot: root });
  assert.equal(r.kind, 'consume');
  assert.ok(r.path.endsWith('definition.md'));
  rmSync(root, { recursive: true, force: true });
});

test('bare + scoped 공존: scope로 정확히 분리 해소', () => {
  const root = tmpProject();
  mkdirSync(join(root, 'docs', 'specs'), { recursive: true });
  writeFileSync(join(root, 'docs', 'specs', 'definition.md'), DEF);
  writeFileSync(join(root, 'docs', 'specs', 'definition.backoffice.md'), DEF.replace('definitionVersion: 2', 'definitionVersion: 5'));
  const bare = checkDefinitionGate({ projectRoot: root });
  const bo = checkDefinitionGate({ projectRoot: root, scope: 'backoffice' });
  assert.equal(bare.definitionVersion, 2);
  assert.equal(bo.definitionVersion, 5);
  rmSync(root, { recursive: true, force: true });
});
