import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  isStale,
  extractBasedOnDefinition,
  extractFromRefs,
  computeImpacted,
  detectDrift
} from '../scripts/definitionPropagation.mjs';

test('isStale: 정의서 버전이 더 크면 stale (정수 소비처)', () => {
  assert.equal(isStale(1, 2), true);
  assert.equal(isStale(2, 2), false);
  assert.equal(isStale(3, 2), false);
});

test('isStale: extractBasedOnDefinition 객체(신규격)도 그대로 받는다', () => {
  const spec = `<!-- basedOnDefinition: ../../definition.md@v1 | IF-15 -->\n# Req`;
  const based = extractBasedOnDefinition(spec);
  assert.equal(isStale(based, 2), true);   // 현재 v2 > based v1 → stale
  assert.equal(isStale(based, 1), false);
});

test('extractBasedOnDefinition: 구 정수형 — version=정수, valueOf로 정수처럼 동작', () => {
  const spec = `<!-- Generated by dt-spec@0.7.0 at 2026-06-09T10:00:00Z -->
<!-- status: draft -->
<!-- sources: figma:0:1@design -->
<!-- specVersion: 1.1 -->
<!-- basedOnDefinition: 3 -->

# Req`;
  const based = extractBasedOnDefinition(spec);
  assert.equal(based.version, 3);
  assert.equal(Number(based), 3);  // valueOf → 3 (산술 강제변환)
  assert.equal(based.path, undefined);
  assert.equal(based.ifIds, undefined);
  assert.equal(3 > based, false);  // 산술 비교 하위호환
  assert.equal(4 > based, true);
});

test('extractBasedOnDefinition: 신규격(경로형) — path·version·ifIds 파싱', () => {
  const spec = `<!-- basedOnDefinition: ../../definition.md@v1 | IF-4,IF-7, IF-15 -->\n# Req`;
  const based = extractBasedOnDefinition(spec);
  assert.equal(based.version, 1);
  assert.equal(based.path, '../../definition.md');
  assert.deepEqual(based.ifIds, ['IF-4', 'IF-7', 'IF-15']);
  assert.equal(Number(based), 1); // valueOf 하위호환
});

test('extractBasedOnDefinition: 신규격 — IF 리스트 없는 경로형도 허용(ifIds=[])', () => {
  const spec = `<!-- basedOnDefinition: ../../definition.md@v2 -->\n# Req`;
  const based = extractBasedOnDefinition(spec);
  assert.equal(based.version, 2);
  assert.equal(based.path, '../../definition.md');
  assert.deepEqual(based.ifIds, []);
});

test('extractBasedOnDefinition: basedOnDefinition 없으면 null (legacy/구버전 spec)', () => {
  const spec = `<!-- Generated by dt-spec@0.7.0 at 2026-06-09T10:00:00Z -->
<!-- status: draft -->
<!-- sources: figma:0:1@design -->
<!-- specVersion: 1.1 -->

# Req`;
  assert.equal(extractBasedOnDefinition(spec), null);
});

test('extractFromRefs: from 역참조 ID 추출', () => {
  const spec = `# Req
FR-1 ... <!-- from: IF-2 -->
FR-2 ... <!-- from: SP-1 -->
FR-3 (no ref)`;
  assert.deepEqual(extractFromRefs(spec), ['IF-2', 'SP-1']);
});

test('computeImpacted: 바뀐 ID를 from으로 가진 항목만 반환', () => {
  const spec = `<!-- from: IF-2 --> <!-- from: SP-1 --> <!-- from: IF-5 -->`;
  const impacted = computeImpacted(['IF-2', 'SP-9'], spec);
  assert.deepEqual(impacted, ['IF-2']); // SP-9는 spec이 참조 안 함 → 제외
});

test('computeImpacted: 영향 없으면 빈 배열', () => {
  const spec = `<!-- from: IF-1 -->`;
  assert.deepEqual(computeImpacted(['IF-9'], spec), []);
});

test('computeImpacted: 신규격 basedOnDefinition IF 리스트를 보조 소스로 합산(FE — from 마커 전무)', () => {
  const spec = `<!-- basedOnDefinition: ../../definition.md@v1 | IF-4,IF-15 -->\n# Req (from 마커 없음)`;
  assert.deepEqual(computeImpacted(['IF-15', 'IF-9'], spec), ['IF-15']);
});

test('computeImpacted: from-refs와 basedOnDefinition IF 리스트 합산·중복 제거', () => {
  const spec = `<!-- basedOnDefinition: ../../definition.md@v1 | IF-15,IF-16 -->
FR-1 <!-- from: IF-15 --> FR-2 <!-- from: SP-3 -->`;
  // IF-15는 양쪽에 있으나 한 번만, IF-16은 basedOnDefinition에서, SP-3은 from에서.
  assert.deepEqual(computeImpacted(['IF-15', 'IF-16', 'SP-3', 'IF-99'], spec).sort(),
    ['IF-15', 'IF-16', 'SP-3']);
});

test('detectDrift: 계약에만 있는 요청 파라미터는 missing', () => {
  const definitionIF = { method: 'GET', requestParams: ['cursor', 'limit', 'keyword'] };
  const deepReadContract = { method: 'GET', requestParams: ['cursor', 'limit', 'keyword', 'sort'] };
  const drift = detectDrift(definitionIF, deepReadContract);
  assert.deepEqual(drift.missing, ['sort']);
  assert.deepEqual(drift.conflicting, []);
});

test('detectDrift: 계약과 정의서 IF가 일치하면 빈 결과', () => {
  const definitionIF = { method: 'GET', requestParams: ['cursor', 'limit'] };
  const deepReadContract = { method: 'GET', requestParams: ['cursor', 'limit'] };
  assert.deepEqual(detectDrift(definitionIF, deepReadContract), { missing: [], conflicting: [] });
});

test('detectDrift: 메서드 불일치는 conflicting', () => {
  const drift = detectDrift({ method: 'GET', requestParams: [] }, { method: 'POST', requestParams: [] });
  assert.deepEqual(drift.missing, []);
  assert.deepEqual(drift.conflicting, ['method: GET≠POST']);
});

test('detectDrift: 계약에만 있는 상태코드는 conflicting', () => {
  const drift = detectDrift(
    { method: 'GET', requestParams: [], statusCodes: ['200'] },
    { method: 'GET', requestParams: [], statusCodes: ['200', '404'] }
  );
  assert.deepEqual(drift.conflicting, ['status: 404']);
});

test('detectDrift: 누락 필드(undefined/빈 객체)에도 안전 — 빈 결과', () => {
  assert.deepEqual(detectDrift({}, {}), { missing: [], conflicting: [] });
  assert.deepEqual(detectDrift(undefined, undefined), { missing: [], conflicting: [] });
});

test('detectDrift: IF-18 정렬 누락 실증 픽스처', () => {
  // 정의서 IF-18은 sort를 빠뜨렸고 deep-read가 정렬 규칙을 발견한 실증 케이스(설계 §1)
  const definitionIF = { method: 'GET', requestParams: ['cursor', 'limit', 'keyword'] };
  const deepReadContract = { method: 'GET', requestParams: ['cursor', 'limit', 'keyword', 'sort'] };
  assert.deepEqual(detectDrift(definitionIF, deepReadContract).missing, ['sort']);
});

test('detectDrift: 응답 shape — 계약에만 있는 응답 필드는 conflicting(shape 접두)', () => {
  const drift = detectDrift(
    { requestParams: [], responseFields: ['id', 'name'] },
    { requestParams: [], responseFields: ['id', 'name', 'thumbnailUrl'] }
  );
  assert.ok(drift.conflicting.some(c => /shape/.test(c) && /thumbnailUrl/.test(c)), JSON.stringify(drift));
});

test('detectDrift: 응답 shape — 한쪽에 responseFields 없으면 shape diff 안 함(R6 가드)', () => {
  const drift = detectDrift(
    { requestParams: [] },                                  // 정의서 IF에 shape 없음(DM 미참조)
    { requestParams: [], responseFields: ['id', 'x', 'y'] } // leaf만 shape 있음
  );
  assert.deepEqual(drift, { missing: [], conflicting: [] }); // 전부-drift 오탐 안 함
});

test('detectDrift: 응답 shape 일치하면 shape conflicting 없음', () => {
  const drift = detectDrift(
    { responseFields: ['id', 'name'] },
    { responseFields: ['id', 'name'] }
  );
  assert.deepEqual(drift.conflicting, []);
});
