import { test } from 'node:test';
import assert from 'node:assert/strict';
import { validateDefinition } from '../scripts/validateDefinition.mjs';

const VALID = `<!-- Generated by dt-devspec@0.7.0 at 2026-06-09T10:00:00Z -->
<!-- status: draft -->
<!-- sources: figma:0:1@design -->
<!-- specVersion: 1.1 -->
<!-- definitionVersion: 1 -->

# 개발 정의서: demo

## 전역 규약 (Global Conventions)
- 에러 응답 포맷: { code, message }

## 범위 분담 (Scope Split)
| ID | 기능/책임 | 담당 | 신뢰도 | 비고 |
|----|----------|------|--------|------|
| SP-1 | 목록 조회 | BE+FE | confident | 검색은 서버 |

## 인터페이스 합의 (Interface Contract)
| ID | 엔드포인트 | 메서드 | 요청 | 응답 | 합의 상태 |
|----|-----------|--------|------|------|----------|
| IF-1 | /api/files | GET | q | { items } | 확정 |

## 변경 추적 (Traceability)
- 각 SP/IF ID는 안정적 키.
`;

test('validateDefinition: 올바른 정의서는 valid', () => {
  const r = validateDefinition(VALID);
  assert.equal(r.valid, true, JSON.stringify(r.errors));
  assert.equal(r.errors.length, 0);
});

test('validateDefinition: 헤더 없으면 kind=hand-authored (에러 아님)', () => {
  const hand = VALID.replace(/<!--[^\n]*-->\n/g, ''); // 헤더 5줄 제거
  const r = validateDefinition(hand);
  assert.equal(r.kind, 'hand-authored');
  assert.equal(r.structureOk, true, JSON.stringify(r));
});

test('validateDefinition: 필수 섹션 누락 시 invalid', () => {
  const noScope = VALID.replace('## 범위 분담 (Scope Split)', '## 다른 섹션');
  const r = validateDefinition(noScope);
  assert.equal(r.valid, false);
  assert.ok(r.errors.some(e => /범위 분담/.test(e)));
});

test('validateDefinition: 잘못된 ID 접두사 감지', () => {
  const badId = VALID.replace('| SP-1 |', '| XX-1 |');
  const r = validateDefinition(badId);
  assert.equal(r.valid, false);
  assert.ok(r.errors.some(e => /ID/.test(e)));
});

test('validateDefinition: 전역 규약 본문의 #PROJ-123 같은 KEY-N 토큰은 표 밖이라 valid (오탐 방지)', () => {
  // WHY: Git 워크플로우 항목의 Jira 키(#PROJ-123)는 표 ID 셀이 아니라 본문 불릿이다.
  // 이 줄에는 파이프(|)가 없어 ID_CELL_REGEX에 애초에 닿지 않는다(표 밖 KEY-N 오탐 방지 회귀).
  const withGit = VALID.replace(
    '- 에러 응답 포맷: { code, message }',
    '- 에러 응답 포맷: { code, message }\n- Git 워크플로우: 커밋 제목 끝에 Jira id (예: `feat: 파일 업로드 추가 #PROJ-123`)'
  );
  const r = validateDefinition(withGit);
  assert.equal(r.valid, true, JSON.stringify(r.errors));
  assert.equal(r.errors.length, 0);
});

test('validateDefinition: 본문 중간에 파이프로 감싼 토큰(| WCAG-2 |)이 있어도 valid (ID_CELL_REGEX 줄-앵커 가드)', () => {
  // WHY: ID_CELL_REGEX의 줄-앵커(^\s*\|)가 load-bearing임을 잠근다. 앵커가 없으면 본문 중간의
  // | WCAG-2 |가 ID 셀로 오탐돼 SP-/IF- 위반(invalid)이 된다. 앵커를 느슨하게 하면 이 테스트가 실패한다.
  const withInlinePipe = VALID.replace(
    '- 에러 응답 포맷: { code, message }',
    '- 에러 응답 포맷: { code, message }\n- 접근성: 표로 적으면 | WCAG-2 | 같은 기준을 따른다'
  );
  const r = validateDefinition(withInlinePipe);
  assert.equal(r.valid, true, JSON.stringify(r.errors));
  assert.equal(r.errors.length, 0);
});

test('validateDefinition: 정상 generated → kind=generated, structureOk', () => {
  const r = validateDefinition(VALID);
  assert.equal(r.kind, 'generated');
  assert.equal(r.structureOk, true);
  assert.equal(r.specVersion, '1.1');
  assert.equal(r.definitionVersion, 1);
});

test('validateDefinition: 너무 대충 손작성(IF 없음) → structureOk:false', () => {
  const rough = '# 대충\n## 전역 규약\n## 범위 분담\n## 인터페이스 합의\n## 변경 추적\n산문만 있음';
  const r = validateDefinition(rough);
  assert.equal(r.kind, 'hand-authored');
  assert.equal(r.structureOk, false);
});

test('validateDefinition: DM-n 행 허용(화이트리스트 +DM)', () => {
  const withDM = VALID.replace(
    '## 변경 추적 (Traceability)',
    '## 데이터 모델 (Data Models)\n| ID | shape |\n| DM-1 | { id, name } |\n\n## 변경 추적 (Traceability)'
  );
  const r = validateDefinition(withDM);
  assert.ok(!r.errors.some(e => /DM-1/.test(e)), JSON.stringify(r.errors));
});

test('validateDefinition: 구버전 generated(specVersion 1.0)는 라벨 어휘 검사 면제', () => {
  const old = VALID
    .replace('<!-- specVersion: 1.1 -->', '<!-- specVersion: 1.0 -->')
    .replace('| 확정 |', '| 옛날어휘 |');
  const r = validateDefinition(old);
  assert.equal(r.specVersion, '1.0');
  assert.equal(r.structureOk, true, '구버전은 구조 무결성만 봄');
});

test('validateDefinition: status는 본문 미해소 잔존으로도 draft (hand-authored)', () => {
  const hand = VALID.replace(/<!--[^\n]*-->\n/g, '').replace('| 확정 |', '| 미해소 |');
  const r = validateDefinition(hand);
  assert.equal(r.status, 'draft');
});

test('validateDefinition: generated인데 status 줄 결손 + 본문 미해소 → draft (헤더 비의존 ⑦)', () => {
  const noStatus = VALID.replace('<!-- status: draft -->\n', '').replace('| 확정 |', '| 미해소 |');
  const r = validateDefinition(noStatus);
  assert.equal(r.kind, 'generated');
  assert.equal(r.status, 'draft');
});

test('validateDefinition: 산문 속 "미해소"는 status에 영향 없음(IF 셀만 스캔 — 설계 §8 ⑦)', () => {
  // WHY: 전역 규약 산문에 '미해소'가 등장해도 IF 셀이 모두 해소면 draft로 오탐하면 안 된다.
  const hand = VALID
    .replace(/<!--[^\n]*-->\n/g, '') // 헤더 제거 → hand-authored
    .replace('- 에러 응답 포맷: { code, message }', '- 미해소 항목은 인터페이스 표에 적는다(규약 산문)');
  const r = validateDefinition(hand);
  assert.equal(r.status, null, 'IF 셀은 확정뿐 → 산문의 미해소로 draft 되면 안 됨');
});

test('validateDefinition: IF 셀의 "미해소(질문완료)" 부분매치는 draft (셀 내부 부분매치 보존)', () => {
  const hand = VALID.replace(/<!--[^\n]*-->\n/g, '').replace('| 확정 |', '| 미해소(질문완료) |');
  const r = validateDefinition(hand);
  assert.equal(r.status, 'draft');
});

test('validateDefinition: 50% 경계 — IF 2행 중 1행 wellFormed → structureOk:true', () => {
  const md = '## 전역 규약\n## 범위 분담\n## 인터페이스 합의\n## 변경 추적\n| IF-1 | 파일 조회 | 협의중 |\n| IF-2 | x |\n';
  const r = validateDefinition(md);
  assert.equal(r.structureOk, true, '1/2 = 50% >= 50% (경계 포함)');
});

test('validateDefinition: IF 3행 중 1행만 wellFormed → structureOk:false', () => {
  const md = '## 전역 규약\n## 범위 분담\n## 인터페이스 합의\n## 변경 추적\n| IF-1 | 파일 조회 | 협의중 |\n| IF-2 | x |\n| IF-3 | y |\n';
  const r = validateDefinition(md);
  assert.equal(r.structureOk, false, '1/3 = 33% < 50%');
});

test('validateDefinition: DM 섹션 없으면 DM 관련 에러 없음(옵셔널)', () => {
  const r = validateDefinition(VALID);
  assert.ok(!r.errors.some(e => /DM/.test(e)), JSON.stringify(r.errors));
});

test('validateDefinition: DM-n 행이 shape 셀 없이 식별자만이면 구조 에러', () => {
  const bad = VALID.replace(
    '## 변경 추적 (Traceability)',
    '## 데이터 모델 (Data Models)\n| ID | shape |\n|----|----|\n| DM-1 |\n\n## 변경 추적 (Traceability)'
  );
  const r = validateDefinition(bad);
  assert.ok(r.errors.some(e => /DM-1/.test(e) && /shape/.test(e)), JSON.stringify(r.errors));
});

test('validateDefinition: 정상 DM-n 행(shape 셀 있음)은 valid', () => {
  const withDM = VALID.replace(
    '## 변경 추적 (Traceability)',
    '## 데이터 모델 (Data Models)\n| ID | shape | 사용 IF |\n|----|----|----|\n| DM-1 | { id:number, name:string } | IF-1 |\n\n## 변경 추적 (Traceability)'
  );
  const r = validateDefinition(withDM);
  assert.equal(r.valid, true, JSON.stringify(r.errors));
});
