import { readFileSync } from 'node:fs';
import { leadingCommentBlock } from './buildDefinitionHeader.mjs';

const pkg = JSON.parse(readFileSync(new URL('../.claude-plugin/plugin.json', import.meta.url)));
export const PLUGIN_VERSION = pkg.version;
const SPEC_VERSION = '1.1';

// WHY: buildSpecHeader signature changed to accept sources array for multi-source support
// WHY: definitionVersion(옵셔널)이 오면 5번째 줄 basedOnDefinition emit — 게이트 통과 spec의 전파 입력.
export function buildSpecHeader({ generatedAt, status, sources, definitionVersion, definitionPath, definitionIfIds, definitionSOT, scope }) {
  if (status !== 'finalized' && status !== 'draft') {
    throw new Error("status must be 'finalized' or 'draft'");
  }
  if (definitionVersion !== undefined &&
      (!Number.isInteger(definitionVersion) || definitionVersion < 1)) {
    throw new Error('definitionVersion must be a positive integer');
  }
  if (definitionPath !== undefined && definitionVersion === undefined) {
    throw new Error('definitionPath requires definitionVersion (신규격은 @v<N> 병기 필수)');
  }
  if (definitionSOT !== undefined && definitionSOT !== 'none' && definitionSOT !== 'unstructured') {
    throw new Error("definitionSOT must be 'none' or 'unstructured'");
  }

  // WHY: sources is array of { type, locator, role?, loadFailed? }
  // Format each source as type:locator[@role][ (load-failed)]
  const sourcesStr = sources.map(src => {
    let entry = `${src.type}:${src.locator}`;
    if (src.role) {
      entry += `@${src.role}`;
    }
    if (src.loadFailed) {
      entry += ' (load-failed)';
    }
    return entry;
  }).join(', ');

  const lines = [
    `<!-- Generated by dt-spec@${PLUGIN_VERSION} at ${generatedAt} -->`,
    `<!-- status: ${status} -->`,
    `<!-- sources: ${sourcesStr} -->`,
    `<!-- specVersion: ${SPEC_VERSION} -->`
  ];
  // WHY: standalone(정식 SOT 없음/unstructured) — basedOnDefinition 대신 경고 주석.
  // 둘은 상호 배타: SOT 없는 산출물은 가리킬 정의서 버전이 없다.
  // WHY: definitionSOT/definitionVersion 둘 다 미전달(legacy 경로)이면 기존 4줄 그대로 → 회귀 없음.
  if (definitionSOT !== undefined) {
    lines.push(`<!-- definitionSOT: ${definitionSOT} -->`);
  } else if (definitionVersion !== undefined) {
    // WHY: definitionPath가 오면 신규격(경로형) — 경로@v<N> [| IF 리스트]로 emit해
    // extractBasedOnDefinition이 path·version·ifIds를 다 읽고 computeImpacted가 IF 리스트를
    // 보조 소스로 쓰게 한다. definitionPath 미전달이면 구 정수형(하위호환).
    if (definitionPath !== undefined) {
      const ifs = Array.isArray(definitionIfIds) ? definitionIfIds.filter(Boolean) : [];
      const ifPart = ifs.length ? ` | ${ifs.join(',')}` : '';
      lines.push(`<!-- basedOnDefinition: ${definitionPath}@v${definitionVersion}${ifPart} -->`);
    } else {
      lines.push(`<!-- basedOnDefinition: ${definitionVersion} -->`);
    }
  }
  // WHY: scope(옵셔널)는 헤더 *마지막*에 emit한다. specVersion 앞에 두면
  // HEADER_REGEX(Generated…specVersion 연속 매칭)가 파손된다(buildSpecHeader.test "실증" 참조).
  if (scope) {
    lines.push(`<!-- scope: ${scope} -->`);
  }
  return lines.join('\n');
}

// WHY: parseSpecHeader now branches on specVersion because old 1.0 and new 1.1 formats have different sources syntax
// Top-level regex captures brand, generatedAt, status, raw sources string, and specVersion
const HEADER_REGEX = /<!-- Generated by (figma-ux-spec|dt-spec)@([\d.]+) at ([^ ]+) -->\s*<!-- status: (finalized|draft) -->\s*<!-- sources: (.+?) -->\s*<!-- specVersion: ([\d.]+) -->/;

export function parseSpecHeader(markdown) {
  const m = markdown.match(HEADER_REGEX);
  if (!m) return null;

  // WHY: scope는 헤더 블록(최상단 연속 주석)만 대상 — 본문 주석 오탐 방지.
  const block = leadingCommentBlock(markdown);
  const scopeMatch = block.match(/<!-- scope: (.+?) -->/);
  const scope = scopeMatch ? scopeMatch[1] : null;

  const brand = m[1];
  const pluginVersion = m[2];
  const generatedAt = m[3];
  const status = m[4];
  const sourcesRaw = m[5];
  const specVersion = m[6];

  // WHY: parse sources differently based on specVersion
  let sources;
  if (specVersion === '1.0') {
    // WHY: 1.0 format is "figmaPageNodeId=X, figmaUxWireframeNodeId=Y"
    // Migrate to sources array with design/wireframe roles
    const pageMatch = sourcesRaw.match(/figmaPageNodeId=([^,]+)/);
    const wireMatch = sourcesRaw.match(/figmaUxWireframeNodeId=(\S+)/);
    sources = [];
    if (pageMatch) {
      sources.push({ type: 'figma', locator: pageMatch[1], role: 'design' });
    }
    if (wireMatch) {
      sources.push({ type: 'figma', locator: wireMatch[1], role: 'wireframe' });
    }
  } else if (specVersion === '1.1') {
    // WHY: 1.1 format is "type:locator[@role][ (load-failed)], ..."
    sources = parseSources1_1(sourcesRaw);
  } else {
    // WHY: unknown version, best-effort attempt using 1.1 parser
    sources = parseSources1_1(sourcesRaw);
  }

  return {
    brand,
    pluginVersion,
    generatedAt,
    status,
    specVersion,
    sources,
    scope
  };
}

// WHY: helper to parse 1.1 format sources string
// Format: type:locator[@role][ (load-failed)], type:locator[@role][ (load-failed)], ...
function parseSources1_1(sourcesStr) {
  return sourcesStr.split(/, /).map(entry => {
    const loadFailedMatch = entry.match(/ \(load-failed\)$/);
    const loadFailed = !!loadFailedMatch;
    const entryWithoutLoadFailed = loadFailedMatch ? entry.slice(0, loadFailedMatch.index) : entry;

    const colonIdx = entryWithoutLoadFailed.indexOf(':');
    if (colonIdx === -1) return null;

    const type = entryWithoutLoadFailed.slice(0, colonIdx);
    const rest = entryWithoutLoadFailed.slice(colonIdx + 1);

    const atIdx = rest.indexOf('@');
    let locator, role;
    if (atIdx === -1) {
      locator = rest;
      role = undefined;
    } else {
      locator = rest.slice(0, atIdx);
      role = rest.slice(atIdx + 1);
    }

    const src = { type, locator };
    if (role) src.role = role;
    if (loadFailed) src.loadFailed = true;
    return src;
  }).filter(Boolean);
}
