import { readFileSync } from 'node:fs';

const pkg = JSON.parse(readFileSync(new URL('../.claude-plugin/plugin.json', import.meta.url)));
export const PLUGIN_VERSION = pkg.version;
export const SPEC_VERSION = '1.2';

export function buildDefinitionHeader({ generatedAt, status, sources, definitionVersion, scope }) {
  if (status !== 'finalized' && status !== 'draft') {
    throw new Error("status must be 'finalized' or 'draft'");
  }
  if (!Number.isInteger(definitionVersion) || definitionVersion < 1) {
    throw new Error('definitionVersion must be a positive integer');
  }
  const sourcesStr = sources.map(src => {
    let entry = `${src.type}:${src.locator}`;
    if (src.role) entry += `@${src.role}`;
    if (src.loadFailed) entry += ' (load-failed)';
    return entry;
  }).join(', ');

  const lines = [
    `<!-- Generated by dt-devspec@${PLUGIN_VERSION} at ${generatedAt} -->`,
    `<!-- status: ${status} -->`,
    `<!-- sources: ${sourcesStr} -->`,
    `<!-- specVersion: ${SPEC_VERSION} -->`,
    `<!-- definitionVersion: ${definitionVersion} -->`
  ];
  // WHY: scope(옵셔널) — 있을 때만 6번째 줄 emit. 없으면 5줄 유지(하위호환).
  if (scope) {
    lines.push(`<!-- scope: ${scope} -->`);
  }
  return lines.join('\n');
}

// WHY: 헤더 블록 = 파일 최상단 연속 HTML 주석 블록(첫 비-주석/공백 줄에서 종료).
// WHY: buildSpecHeader.parseSpecHeader도 scope 추출에 재사용(DRY) — export.
export function leadingCommentBlock(markdown) {
  const lines = markdown.split('\n');
  const block = [];
  for (const line of lines) {
    if (/^\s*<!--.*-->\s*$/.test(line)) { block.push(line); continue; }
    break; // 첫 비-주석/공백 줄에서 종료
  }
  return block.join('\n');
}

// WHY: specVersion·definitionVersion 줄은 옵셔널(구버전/레거시 generated 대비).
// kind 판정에 쓰는 Generated 마커만 필수 — 없으면 null(=hand-authored).
export function parseDefinitionHeader(markdown) {
  const block = leadingCommentBlock(markdown);
  // kind 판정용 Generated 마커는 정형 마커 줄 전체 앵커(^...$/m)로 매칭 — 부분문자열 contains 금지.
  const gen = block.match(/^\s*<!--\s*Generated by dt-devspec@([\d.]+) at (\S+)\s*-->\s*$/m);
  if (!gen) return null;
  const status = block.match(/<!-- status: (finalized|draft) -->/);
  const sources = block.match(/<!-- sources: (.+?) -->/);
  const spec = block.match(/<!-- specVersion: ([\d.]+) -->/);
  const defVer = block.match(/<!-- definitionVersion: (\d+) -->/);
  const scope = block.match(/<!-- scope: (.+?) -->/);
  return {
    pluginVersion: gen[1],
    generatedAt: gen[2],
    status: status ? status[1] : null,
    sourcesRaw: sources ? sources[1] : null,
    specVersion: spec ? spec[1] : null,
    definitionVersion: defVer ? parseInt(defVer[1], 10) : null,
    scope: scope ? scope[1] : null
  };
}
